var TK=TK||{};
TK.EventDispatcher=function(c){var k={};c.dispatcher={};c.dispatcher.eventListeners={};c.dispatcher.backupListerners={};k.addEventListener=function(g,a,d){void 0!==g&&null!==g&&(void 0===c.dispatcher.eventListeners[g]&&(c.dispatcher.eventListeners[g]=[]),c.dispatcher.eventListeners[g].push(a),d&&(void 0===c.dispatcher.backupListerners[d]&&(c.dispatcher.backupListerners[d]=[]),c.dispatcher.backupListerners[d].push({eventType:g,listener:a})))};k.removeEventListener=function(g,a){c.dispatcher.eventListeners[g]?(a=
c.dispatcher.eventListeners[g].indexOf(a),-1!==a&&c.dispatcher.eventListeners[g].splice(a,1)):L.Logger.info("[tk-fake-sdk]not event type: "+g)};k.removeAllEventListener=function(g){if(g&&"object"===typeof g&&"number"===typeof g.length&&"function"===typeof g.splice&&!g.propertyIsEnumerable("length"))for(var a in g){var d=g[a];delete c.dispatcher.eventListeners[d]}else if("string"===typeof g)delete c.dispatcher.eventListeners[g];else if("object"===typeof g)for(var b in g)d=b,k.removeEventListener(d,
g[b])};k.dispatchEvent=function(g,a){var d;(void 0!=a?a:1)&&L.Logger.debug("[tk-fake-sdk]dispatchEvent , event type: "+g.type);for(d in c.dispatcher.eventListeners[g.type])if(c.dispatcher.eventListeners[g.type].hasOwnProperty(d))c.dispatcher.eventListeners[g.type][d](g)};k.removeBackupListerner=function(g){if(g&&c.dispatcher.backupListerners[g]){for(var a=0;a<c.dispatcher.backupListerners[g].length;a++){var d=c.dispatcher.backupListerners[g][a];k.removeEventListener(d.eventType,d.listener)}c.dispatcher.backupListerners[g].length=
0;delete c.dispatcher.backupListerners[g]}};return k};TK.TalkEvent=function(c){var k={};k.type=c.type;return k};TK.RoomEvent=function(c,k){var g=TK.TalkEvent(c);g.streams=c.streams;g.message=c.message;g.user=c.user;if(k&&"object"===typeof k)for(var a in k)g[a]=k[a];return g};TK.StreamEvent=function(c,k){var g=TK.TalkEvent(c);g.stream=c.stream;g.message=c.message;g.bandwidth=c.bandwidth;g.attrs=c.attrs;if(k&&"object"===typeof k)for(var a in k)g[a]=k[a];return g};
TK.PublisherEvent=function(c,k){c=TK.TalkEvent(c);if(k&&"object"===typeof k)for(var g in k)c[g]=k[g];return c};TK.clientSdkEventManager=TK.EventDispatcher({});TK.clientUICoreEventManager=TK.EventDispatcher({});TK.mobileSdkEventManager=TK.EventDispatcher({});TK.mobileUICoreEventManager=TK.EventDispatcher({});TK=TK||{};TK.SDKTYPE=void 0;TK.isOnlyAudioRoom=!1;TK.extendSendInterfaceName="";TK.SDKNATIVENAME=void 0;TK.global={fakeJsSdkInitInfo:{debugLog:!1,playback:!1,deviceType:void 0,mobileInfo:{isSendLogMessageToProtogenesis:!1,clientType:void 0}}};TK.QtNativeClientRoom=function(c){TK.SDKNATIVENAME="QtNativeClientRoom";TK.SDKTYPE="pc";return TK.Room(c)};TK.MobileNativeRoom=function(c){TK.SDKNATIVENAME="MobileNativeRoom";TK.SDKTYPE="mobile";return TK.Room(c)};
TK.Room=function(c){function k(l,a,b){L.Logger.debug("[tk-fake-sdk]sendMessageSocket",l,a);e.socket.emit(l,a,b)}function g(l){if(m)for(a in l)l[a].playbackLeaved=!0;else for(var a in l)delete l[a]}function a(l){if(!m)for(var a in l)delete l[a]}function d(l,a){TK.isOnlyAudioRoom!==l&&(TK.isOnlyAudioRoom=l,l=TK.RoomEvent({type:"room-audiovideostate-switched",message:{fromId:a,onlyAudio:TK.isOnlyAudioRoom}}),e.dispatchEvent(l))}function b(){if(r===window.TK.ROOM_MODE.BIG_ROOM)for(var l in h)l!==f.id&&
h[l].role!==window.TK.ROOM_ROLE.TEACHER&&h[l].role!==window.TK.ROOM_ROLE.ASSISTANT&&h[l].publishstate===TK.PUBLISH_STATE_NONE&&delete h[l]}if(TK.SDKNATIVENAME){TK.SDKVERSIONS="2.1.8";TK.SDKVERSIONSTIME="2018032915";L.Logger.info("[tk-sdk-version]sdk-version:"+TK.SDKVERSIONS+" , sdk-time: "+TK.SDKVERSIONSTIME);var e=TK.EventDispatcher({}),f={},h={},p={},m=!1,n={},v=void 0,w=void 0,x=void 0,t=void 0,u=void 0,C=void 0,y=void 0,z=void 0,D=void 0,A=void 0,B=void 0,q=void 0,E={},r=window.TK.ROOM_MODE.NORMAL_ROOM;
e.socket=TK.fakeScoketIO(e);e.setLogIsDebug=function(l,a){l=l||!1;void 0!==a&&(l=0===a?!0:!1);TK.tkLogPrintConfig({debug:l},{development:l,logLevel:void 0!==a&&"number"===typeof a?a:l?L.Constant.LOGLEVEL.DEBUG:L.Constant.LOGLEVEL.INFO},{webrtcLogDebug:l})};e.getRoomProperties=function(){return p};e.getUsers=function(){return h};e.getUser=function(a){if(void 0!==a)return h[a]};e.getMySelf=function(){return f};e.changeExtendSendInterfaceName=function(a){TK.extendSendInterfaceName=a};e.startShareMedia=
function(a,b,d,e){if(a){var l={type:"media"};void 0!==d&&(l.toID=d);if(e&&"object"===typeof e)for(var c in e)"toID"!==c&&"type"!==c&&(l[c]=e[c]);k("publishNetworkMedia",{audio:!0,video:void 0!==b?b:!1,url:a,attributes:l})}else L.Logger.error("[tk-fake-sdk]startShareMedia url can not be empty!")};e.stopShareMedia=function(){k("unpublishNetworkMedia")};e.onPageFinished=function(){k("onPageFinished")};e.pubMsg=function(a){if("object"!==typeof a)L.Logger.error("[tk-sdk]pubMsg params must is json!");else{var b=
{};b.name=a.name||a.msgName;b.id=a.id||a.msgId||b.name;b.toID=a.toID||a.toId||"__all";b.data=a.data;a.save||(b.do_not_save="");void 0!==a.associatedMsgID&&(b.associatedMsgID=a.associatedMsgID);void 0!==a.associatedUserID&&(b.associatedUserID=a.associatedUserID);var l={},d;for(d in a)void 0===b[d]&&"save"!==d&&"name"!==d&&"msgName"!==d&&"id"!==d&&"msgId"!==d&&"toID"!==d&&"toId"!==d&&"data"!==d&&"associatedMsgID"!==d&&"associatedUserID"!==d&&(l[d]=a[d]);b.expandParams=l;k("pubMsg",b)}};e.delMsg=function(a){if(1===
arguments.length&&a&&"object"===typeof a){var b=a.name||a.msgName;var d=a.id||a.msgId;var l=a.toID||a.toId;var e=a.data}else b=arguments[0],d=arguments[1],l=arguments[2],e=arguments[3];var c={};c.name=b;c.id=d||c.name;c.toID=l||"__all";c.data=e;void 0===c.name||null===c.name?L.Logger.error("[tk-fake-sdk]delMsg name is must exist!"):void 0===c.id||null===c.id?L.Logger.error("[tk-fake-sdk]delMsg id is must exist!"):k("delMsg",c)};e.changeUserProperty=function(a,b,d){if(!TK.isOnlyAudioRoom||void 0===
d.publishstate||d.publishstate!==TK.PUBLISH_STATE_VIDEOONLY&&d.publishstate!==TK.PUBLISH_STATE_BOTH)if(void 0===d||void 0===a)L.Logger.error("[tk-fake-sdk]changeUserProperty properties or id is not exist!");else{var l={};l.id=a;l.toID=b||"__all";h[a]?d&&"object"===typeof d?(l.properties=d,k("setProperty",l)):L.Logger.error("[tk-fake-sdk]properties must be json , user id: "+a+"!"):L.Logger.error("[tk-fake-sdk]user is not exist , user id: "+a+"!")}else L.Logger.warning("[tk-fake-sdk]The publishstate of a pure audio room cannot be "+
d.publishstate+"!")};e.changeWebPageFullScreen=function(a){k("changeWebPageFullScreen",{fullScreen:a})};e.leaveroom=function(a){k("leaveroom",{force:a||!1})};e.sendMessage=function(a,b,d){var l={};l.toID=b||"__all";b={};"string"===typeof a&&(a=L.Utils.toJsonParse(a));if("object"===typeof a)for(var e in a)b[e]=a[e];else b.msg=a;"string"===typeof d&&(d=L.Utils.toJsonParse(d));if(d&&"object"===typeof d)for(e in d)b[e]=d[e];l.message=L.Utils.toJsonStringify(b);k("sendMessage",l)};e.sendActionCommand=
function(a,b){a?k("sendActionCommand",{action:a,cmd:b}):L.Logger.warning("[tk-fake-sdk]sendActionCommand method action can not be empty!")};e.setLocalStorageItem=function(a,b){k("saveValueByKey",{key:""+a,value:""+b})};e.getLocalStorageItem=function(a,b){var d=void 0;"function"===typeof b&&(d=function(a){b(""+a)});k("getValueByKey",{key:""+a},d)};e.exitAnnotation=function(a){"string"!==typeof a?L.Logger.error("[tk-fake-sdk]state is not a string"):k("exitAnnotation",a)};e.registerRoomWhiteBoardDelegate=
function(a){if(a&&"TKWhiteBoardManager"===a.className&&"function"===typeof a.registerRoomDelegate){if(q=a)q.registerRoomDelegate&&q.registerRoomDelegate(e,function(a,b){L.Logger.debug("[tk-sdk]receive whiteboard sdk action command\uff08action,cmd\uff09:",a,b);e.sendActionCommand(a,b)}),q.changeCommonWhiteBoardConfigration&&(a={},x&&t&&void 0!==u&&(a.webAddress=x+"://"+t+":"+u),C&&y&&void 0!==z&&(a.webAddress=x+"://"+t+":"+u),D&&A&&void 0!==B&&(a.webAddress=x+"://"+t+":"+u),void 0!==f.id&&(a.myUserId=
f.id),void 0!==f.nickname&&(a.myName=f.nickname),void 0!==f.role&&(a.myRole=f.role),a.isPlayback=m,q.changeCommonWhiteBoardConfigration(a))}else L.Logger.warning("[tk-sdk]register whiteboardManagerInstance not is a TKWhiteBoardManager instance class , cannot execute registerRoomWhiteBoardDelegate method.")};E={setProperty:function(a){L.Logger.debug("[tk-fake-sdk]setProperty info:",L.Utils.toJsonStringify(a));var b=a.id;if(a.hasOwnProperty("properties")){var d=a.properties,l=h[b];f.id===b&&(l=f);if(void 0===
l)L.Logger.error("[tk-fake-sdk]setProperty user is not exist , userid is "+b+"!");else{for(var c in d)"id"!==c&&"watchStatus"!==c&&(l[c]=d[c]);a=TK.RoomEvent({type:"room-userproperty-changed",user:l,message:d},{fromID:a.fromID});e.dispatchEvent(a);r===window.TK.ROOM_MODE.BIG_ROOM&&b!==f.id&&h[b].role!==window.TK.ROOM_ROLE.TEACHER&&h[b].role!==window.TK.ROOM_ROLE.ASSISTANT&&h[b].publishstate===TK.PUBLISH_STATE_NONE&&delete h[b]}}},participantLeft:function(a,b){L.Logger.debug("[tk-fake-sdk]participantLeft userid:"+
a);var d=h[a];void 0===d?L.Logger.error("[tk-fake-sdk]participantLeft user is not exist , userid is "+a+"!"):(L.Logger.info("[tk-fake-sdk]user leave room  , user info: "+L.Utils.toJsonStringify(d)),m&&void 0!==b&&(d.leaveTs=b),n[d.role]||(n[d.role]={}),m?h[a]&&(h[a].playbackLeaved=!0):(delete n[d.role][a],delete h[a]),m&&"object"===typeof a&&(d.leaveTs=a.ts),a=TK.RoomEvent({type:"room-participant_leave",user:d}),e.dispatchEvent(a))},participantJoined:function(a){L.Logger.debug("[tk-fake-sdk]participantJoined userinfo:"+
L.Utils.toJsonStringify(a));var b=TK.RoomUser(a);L.Logger.info("[tk-fake-sdk]user join room  , user info: "+L.Utils.toJsonStringify(b));n[b.role]||(n[b.role]={});n[b.role][b.id]=b;h[b.id]=b;m&&h[b.id]&&delete h[b.id].playbackLeaved;m&&"object"===typeof a&&(b.joinTs=a.ts);a=TK.RoomEvent({type:"room-participant_join",user:b});e.dispatchEvent(a)},participantEvicted:function(a){a=a||{};L.Logger.info("[tk-fake-sdk]user evicted room  , user info: "+L.Utils.toJsonStringify(f)+" , participantEvicted  messages:"+
L.Utils.toJsonStringify(a));a=TK.RoomEvent({type:"room-participant_evicted",message:a,user:f});e.dispatchEvent(a)},pubMsg:function(a){L.Logger.debug("[tk-fake-sdk]pubMsg info:",L.Utils.toJsonStringify(a));a&&"string"===typeof a&&(a=L.Utils.toJsonParse(a));a.data&&"string"===typeof a.data&&(a.data=L.Utils.toJsonParse(a.data));"OnlyAudioRoom"===a.name&&d(!0,a.fromID);if("BigRoom"===a.name){r=window.TK.ROOM_MODE.BIG_ROOM;b();var l=TK.RoomEvent({type:"room-mode-changed",message:{roomMode:r}});e.dispatchEvent(l)}l=
TK.RoomEvent({type:"room-pubmsg",message:a});e.dispatchEvent(l)},delMsg:function(a){L.Logger.debug("[tk-fake-sdk]delMsg info:",L.Utils.toJsonStringify(a));a&&"string"===typeof a&&(a=L.Utils.toJsonParse(a));a.data&&"string"===typeof a.data&&(a.data=L.Utils.toJsonParse(a.data));"OnlyAudioRoom"===a.name&&d(!1,a.fromID);if("BigRoom"===a.name){r=window.TK.ROOM_MODE.NORMAL_ROOM;b();var c=TK.RoomEvent({type:"room-mode-changed",message:{roomMode:r}});e.dispatchEvent(c)}c=TK.RoomEvent({type:"room-delmsg",
message:a});e.dispatchEvent(c)},sendMessage:function(a){L.Logger.debug("[tk-fake-sdk]room-text-message info:"+(a&&"object"===typeof a?L.Utils.toJsonStringify(a):a));if(a&&a.hasOwnProperty("message")){var b=a.fromID,d=f;if(10===p.roomtype)d=void 0;else if(void 0!==b&&(d=h[a.fromID]),!d){L.Logger.error("[tk-fake-sdk]user is not exist , user id:"+a.fromID+", message from room-text-message!");return}m&&(b=!1,a&&a.message&&"string"===typeof a.message&&(a.message=L.Utils.toJsonParse(a.message),b=!0),a.message.ts=
a.ts,b&&"object"===typeof a.message&&(a.message=L.Utils.toJsonStringify(a.message)));a&&a.message&&"string"===typeof a.message&&(a.message=L.Utils.toJsonParse(a.message));a=TK.RoomEvent({type:"room-text-message",user:d,message:a.message});e.dispatchEvent(a)}else L.Logger.error("[tk-fake-sdk]room-text-message messages or messages.message is not exist!")},roomConnected:function(a,c){L.Logger.debug("[tk-fake-sdk]room-connected code is "+a+" , response is :"+L.Utils.toJsonStringify(c));if(0!==a)L.Logger.error("[tk-fake-sdk]connectSocket failure , code is "+
a+" , response is "+c);else{var l=c.roominfo;a=c.msglist;var g=c.userlist;e.p2p=l.p2p;l=l.id;h={};n={};n[f.role]||(n[f.role]={});n[f.role][f.id]=f;h[f.id]=f;for(var k in g)if(g.hasOwnProperty(k)){var p=TK.RoomUser(g[k]);void 0!==p&&(n[p.role]||(n[p.role]={}),n[p.role][p.id]=p,h[p.id]=p,m&&h[p.id]&&delete h[p.id].playbackLeaved,L.Logger.info("[tk-fake-sdk]room-connected --\x3e user info: "+L.Utils.toJsonStringify(p)))}L.Logger.info("[tk-fake-sdk]room-connected --\x3e myself info: "+L.Utils.toJsonStringify(f));
g=[];a&&"string"==typeof a&&(a=L.Utils.toJsonParse(a));a.hasOwnProperty("OnlyAudioRoom")&&d(!0,a.OnlyAudioRoom.fromID);a.hasOwnProperty("BigRoom")?(r=window.TK.ROOM_MODE.BIG_ROOM,b()):r=window.TK.ROOM_MODE.NORMAL_ROOM;p=TK.RoomEvent({type:"room-mode-changed",message:{roomMode:r}});e.dispatchEvent(p);for(k in a)a.hasOwnProperty(k)&&g.push(a[k]);g.sort(function(a,b){return void 0!==a&&a.hasOwnProperty("seq")&&void 0!==b&&b.hasOwnProperty("seq")?a.seq-b.seq:0});e.roomID=l;L.Logger.debug("[tk-fake-sdk]Connected to room "+
e.roomID);L.Logger.debug("[tk-fake-sdk]connected response:",L.Utils.toJsonStringify(c));L.Logger.info("[tk-fake-sdk]room-connected  signalling list length "+g.length);q&&q.changeCommonWhiteBoardConfigration&&q.changeCommonWhiteBoardConfigration({webAddress:x+"://"+t+":"+u,docAddress:C+"://"+y+":"+z,backupDocAddress:D+"://"+A+":"+B,myUserId:f.id,myName:f.nickname,myRole:f.role,isConnectedRoom:!0,isPlayback:m});c=TK.RoomEvent({type:"room-connected",streams:[],message:g});e.dispatchEvent(c);return!0}},
disconnect:function(b){L.Logger.debug("[tk-fake-sdk]room-disconnected");void 0!=h&&(a(n),g(h));f&&(f.publishstate=TK.PUBLISH_STATE_NONE);q&&q.changeCommonWhiteBoardConfigration&&q.changeCommonWhiteBoardConfigration({isConnectedRoom:!1});b=TK.RoomEvent({type:"room-disconnected",message:b||"unexpected-disconnection"});e.dispatchEvent(b)},reconnecting:function(a){L.Logger.debug("[tk-fake-sdk]reconnecting info:",a);a=TK.RoomEvent({type:"room-reconnecting",message:{number:a,info:"room-reconnecting number:"+
a}});e.dispatchEvent(a)},reconnected:function(a){a=TK.RoomEvent({type:"room-reconnected",message:a});e.dispatchEvent(a)},leaveroom:function(a){q&&q.changeCommonWhiteBoardConfigration&&q.changeCommonWhiteBoardConfigration({isConnectedRoom:!1});a=TK.RoomEvent({type:"room-leaveroom",message:a});e.dispatchEvent(a)},checkroom:function(a){var b={},d=a.result;if(0==d){var c=a.room;var h=a.pullinfo;c.roomtype=Number(c.roomtype);c.maxvideo=parseInt(c.maxvideo);a.roomrole=Number(a.roomrole);var l={},g={};if(h&&
h.data&&h.data.pullConfigureList){var k=h.data.pullConfigureList,n;for(n in k){var q=k[n];l[q.pullProtocol]=q.pullUrlList}}if(h&&h.data&&h.data.pushConfigureInfo)for(n in h=h.data.pushConfigureInfo,h)k=h[n],g[k.pushProtocol]=k;c.pullConfigure=l;c.pushConfigure=g;p=c;v=c.maxvideo;b.properties={};b.properties.role=a.roomrole;b.properties.nickname=a.nickname;l=a.thirdid;void 0!==l&&"0"!=l&&""!=l&&(b.id=l);f=TK.RoomUser(b);m?(w=c.serial+"_"+f.id)&&-1===w.indexOf(":playback")&&(w+=":playback"):w=c.serial;
L.Logger.info("[tk-fake-sdk]"+(m?"initPlaybackInfo to checkroom finshed--\x3e":"")+"_room_max_videocount:"+v,"my id:"+f.id,"room id:"+w,"room properties chairmancontrol is:"+(p.chairmancontrol?window.__TkSdkBuild__?L.Utils.encrypt(p.chairmancontrol):p.chairmancontrol:void 0))}else L.Logger.warning("[tk-fake-sdk]checkroom failure code is "+d);a=TK.RoomEvent({type:m?"room-checkroom-playback":"room-checkroom",message:{ret:d,userinfo:b,roominfo:a}});e.dispatchEvent(a)},updateWebAddressInfo:function(a){x=
a.web_protocol||x;t=a.web_host||t;u=a.web_port||u;C=a.doc_protocol||C;y=a.doc_host||y;z=a.doc_port||z;D=a.backup_doc_protocol||D;A=a.backup_doc_host||A;B=a.backup_doc_port||B;void 0===y&&(y=t);void 0===z&&(z=u);void 0===A&&(A=t);void 0===B&&(B=u);q&&q.changeCommonWhiteBoardConfigration&&q.changeCommonWhiteBoardConfigration({webAddress:x+"://"+t+":"+u,docAddress:C+"://"+y+":"+z,backupDocAddress:D+"://"+A+":"+B});a=TK.RoomEvent({type:"room-serveraddress-update",message:{web_protocol:x,web_host:t,web_port:u,
doc_protocol:C,doc_host:y,doc_port:z,backup_doc_protocol:D,backup_doc_host:A,backup_doc_port:B}});e.dispatchEvent(a)},updateFakeJsSdkInitInfo:function(a){for(var b in a){var d=a[b];if(d&&"object"===typeof d){TK.global.fakeJsSdkInitInfo[b]=TK.global.fakeJsSdkInitInfo[b]||{};for(var c in d)TK.global.fakeJsSdkInitInfo[b][c]=d[c]}else TK.global.fakeJsSdkInitInfo[b]=d}a.debugLog&&e.setLogIsDebug(TK.global.fakeJsSdkInitInfo.debugLog);m=TK.global.fakeJsSdkInitInfo.playback;q&&q.changeCommonWhiteBoardConfigration&&
q.changeCommonWhiteBoardConfigration({isPlayback:m});a=TK.RoomEvent({type:"room-updateFakeJsSdkInitInfo",message:a});e.dispatchEvent(a)},receiveActionCommand:function(a,b){a=TK.RoomEvent({type:"room-receiveActionCommand",message:{action:a,cmd:b}});e.dispatchEvent(a)},playback_clearAll:function(){if(m){r=window.TK.ROOM_MODE.NORMAL_ROOM;var b=TK.RoomEvent({type:"room-mode-changed",message:{roomMode:r}});e.dispatchEvent(b);b=TK.RoomEvent({type:"room-playback-clear_all"});e.dispatchEvent(b);m?(void 0!=
h&&(a(n),g(h)),null!=f&&(f.publishstate=TK.PUBLISH_STATE_NONE)):L.Logger.error("[tk-fake-sdk]No playback environment, no execution playbackClearAll!")}else L.Logger.warning("[tk-sdk]No playback environment!")},duration:function(a){m?(a=TK.RoomEvent({type:"room-playback-duration",message:a}),e.dispatchEvent(a)):L.Logger.warning("[tk-sdk]No playback environment!")},playbackEnd:function(){if(m){var a=TK.RoomEvent({type:"room-playback-playbackEnd"});e.dispatchEvent(a)}else L.Logger.warning("[tk-sdk]No playback environment!")},
playback_updatetime:function(a){m?(a=TK.RoomEvent({type:"room-playback-playback_updatetime",message:a}),e.dispatchEvent(a)):L.Logger.warning("[tk-sdk]No playback environment!")},msgList:function(a){L.Logger.debug("[tk-sdk]msgList info:",L.Utils.toJsonStringify(a));a=TK.RoomEvent({type:"room-msglist",message:a});e.dispatchEvent(a)},participantPublished:function(a){"string"===typeof a&&(a=L.Utils.toJsonParse(a));L.Logger.debug("[tk-sdk]participantPublished userinfo:"+L.Utils.toJsonStringify(a));if(r===
window.TK.ROOM_MODE.BIG_ROOM){var b=TK.RoomUser(a),d=h[b.id];if(d)for(var c in b)d[c]=b[c];else d=b;h[d.id]=d;m&&"object"===typeof a&&(d.joinTs=a.ts)}}};e.setLogIsDebug(TK.global.fakeJsSdkInitInfo.debugLog);if("QtNativeClientRoom"===TK.SDKNATIVENAME)try{qt&&qt.webChannelTransport&&new QWebChannel(qt.webChannelTransport,function(a){window.qtContentTkClient=a.objects.bridge;for(var b in E)e.socket.on(b,E[b]);e.socket.bindAwitSocketListEvent();L.Logger.debug("[tk-sdk]qtWebChannel init finshed!");a=TK.RoomEvent({type:"room-qtWebChannel-finshed"});
e.dispatchEvent(a)})}catch(l){L.Logger.error("[tk-fake-sdk]qt or qt.webChannelTransport is not exist  ")}else for(var F in E)e.socket.on(F,E[F]);return e}L.Logger.error("[tk-fake-sdk]Room is not init!")};
(function(){var c=!1;if(void 0!==window.__SDKDEV__&&null!==window.__SDKDEV__&&"boolean"===typeof window.__SDKDEV__)try{c=window.__SDKDEV__}catch(g){c=!1}if(!c){c=decodeURIComponent(window.location.href);var k=c.indexOf("?");c=c.substring(k+1).match(/(^|&)debug=([^&]*)(&|$)/i);c=null!=c?c[2]:""}window.__TkSdkBuild__=!c;window.localStorage&&window.localStorage.setItem("debug",c?"*":"none")})();TK=TK||{};TK.PUBLISH_STATE_NONE=0;TK.PUBLISH_STATE_AUDIOONLY=1;TK.PUBLISH_STATE_VIDEOONLY=2;TK.PUBLISH_STATE_BOTH=3;TK.PUBLISH_STATE_MUTEALL=4;TK.RoomUser=function(c){if(void 0==c||void 0===c.properties)L.Logger.warning("[tk-fake-sdk]Invalidate user info",k,g);else{var k=c.id,g=c.properties;L.Logger.debug("[tk-fake-sdk]RoomUser",k,g);c={};c.id=k;c.watchStatus=0;for(var a in g)"id"!=a&&"watchStatus"!=a&&(c[a]=g[a]);c.publishstate=c.publishstate||TK.PUBLISH_STATE_NONE;return c}};var L=L||{};TK=TK||{};
L.Logger=function(c){var k="",g=!1;var a=function(a,b){try{switch(b){case c.Logger.DEBUG:g?console.warn.apply(console,a):console.debug.apply(console,a);break;case c.Logger.TRACE:console.trace.apply(console,a);break;case c.Logger.INFO:g?console.warn.apply(console,a):console.info.apply(console,a);break;case c.Logger.WARNING:console.warn.apply(console,a);break;case c.Logger.ERROR:console.error.apply(console,a);break;case c.Logger.NONE:console.warn("log level is none!");break;default:g?console.warn.apply(console,
a):console.log.apply(console,a)}}catch(e){console.log.apply(console,a)}};return{DEBUG:0,TRACE:1,INFO:2,WARNING:3,ERROR:4,NONE:5,setLogDevelopment:function(a){g=a},enableLogPanel:function(){c.Logger.panel=document.createElement("textarea");c.Logger.panel.setAttribute("id","licode-logs");c.Logger.panel.setAttribute("style","position:fixed;left:0;top:0;width: 100%; height: 100%; display: none;z-index:9999;  user-select: text ;-webkit-user-select: text; -moz-user-select: text ; -ms-user-select: text ;");
c.Logger.panel.setAttribute("rows",20);c.Logger.panel.setAttribute("cols",20);c.Logger.panel.setAttribute("readOnly",!0);"QtNativeClientRoom"===TK.SDKNATIVENAME&&(document.oncontextmenu=null,document.oncontextmenu=function(){return!0});var a=document.createElement("button");a.innerHTML="open log";a.setAttribute("style","position:fixed;left:0;top:0;z-index:10000;background:gold;");a.onclick=function(){"open log"===a.innerHTML?(c.Logger.panel.style.display="block",a.innerHTML="close log"):(c.Logger.panel.style.display=
"none",a.innerHTML="open log")};document.body.appendChild(a);document.body.appendChild(c.Logger.panel)},setLogLevel:function(a){a>c.Logger.NONE?a=c.Logger.NONE:a<c.Logger.DEBUG&&(a=c.Logger.DEBUG);c.Logger.logLevel=a},setOutputFunction:function(d){a=d},setLogPrefix:function(a){k=a},print:function(d){var b=k;if(!(d<c.Logger.logLevel)){d===c.Logger.DEBUG?b=b+"DEBUG("+(new Date).toLocaleString()+")":d===c.Logger.TRACE?b=b+"TRACE("+(new Date).toLocaleString()+")":d===c.Logger.INFO?b=b+"INFO("+(new Date).toLocaleString()+
")":d===c.Logger.WARNING?b=b+"WARNING("+(new Date).toLocaleString()+")":d===c.Logger.ERROR&&(b=b+"ERROR("+(new Date).toLocaleString()+")");b+=":";for(var e=[],f=0;f<arguments.length;f++)e[f]=arguments[f];e=e.slice(1);e=[b].concat(e);if(void 0!==c.Logger.panel){b="";for(f=0;f<e.length;f++)b+="object"===typeof e[f]?c.Utils.toJsonStringify(e[f]):e[f];c.Logger.panel.value=c.Logger.panel.value+"\n"+b}a.apply(c.Logger,[e,d])}},debug:function(){for(var a=[],b=0;b<arguments.length;b++)a[b]=arguments[b];c.Logger.print.apply(c.Logger,
[c.Logger.DEBUG].concat(a))},trace:function(){for(var a=[],b=0;b<arguments.length;b++)a[b]=arguments[b];c.Logger.print.apply(c.Logger,[c.Logger.TRACE].concat(a))},info:function(){for(var a=[],b=0;b<arguments.length;b++)a[b]=arguments[b];c.Logger.print.apply(c.Logger,[c.Logger.INFO].concat(a))},warning:function(){for(var a=[],b=0;b<arguments.length;b++)a[b]=arguments[b];c.Logger.print.apply(c.Logger,[c.Logger.WARNING].concat(a))},error:function(){for(var a=[],b=0;b<arguments.length;b++)a[b]=arguments[b];
c.Logger.print.apply(c.Logger,[c.Logger.ERROR].concat(a))}}}(L);TK.tkLogPrintConfig=function(c,k,g){k=k||{};c=c||{};g=g||{};var a=void 0!=k.logLevel?k.logLevel:0;c=void 0!=c.debug?c.debug:!0;g=void 0!=g.webrtcLogDebug?g.webrtcLogDebug:!0;L.Logger.setLogDevelopment(void 0!=k.development?k.development:!0);L.Logger.setLogLevel(a);L.Utils.localStorage&&L.Utils.localStorage.setItem("debug",c?"*":"none");window.webrtcLogDebug=g};L=L||{};L.Constant=function(){return{clientType:{ios:"ios",android:"android"},IOS:"ios",ANDROID:"android",LOGLEVEL:{DEBUG:0,TRACE:1,INFO:2,WARNING:3,ERROR:4,NONE:5}}}(L);window.TK=window.TK||{};window.TK_ERR={DEVICE_ERROR_UnknownError:1E4,DEVICE_ERROR_NotFoundError:10001,DEVICE_ERROR_NotAllowedError:10002,DEVICE_ERROR_NotReadableError:10003,DEVICE_ERROR_OverconstrainedError:10004,DEVICE_ERROR_TypeError:10005,TIMEOUT_ERROR:10006};window.TK_VIDEO_MODE={ASPECT_RATIO_CONTAIN:20001,ASPECT_RATIO_COVER:20002};window.TK.ROOM_ROLE={TEACHER:0,ASSISTANT:1,STUDENT:2,AUDIT:3,PATROL:4,SYSTEM_ADMIN:10,ENTERPRISE_ADMIN:11,ADMIN:12,PLAYBACK:-1};
window.TK.ROOM_MODE={NORMAL_ROOM:"normalRoom",BIG_ROOM:"bigRoom"};
window.TK.ERROR_NOTICE={PUBLISH_AUDIO_VIDEO_FAILURE:40001,SHARE_MEDIA_FAILURE:40003,SHARE_FILE_FAILURE:40004,SHARE_SCREEN_FAILURE:40005,SUBSCRIBE_AUDIO_VIDEO_FAILURE:40007,SUBSCRIBE_MEDIA_FAILURE:40008,SUBSCRIBE_FILE_FAILURE:40009,SUBSCRIBE_SCREEN_FAILURE:40010,UNSUBSCRIBE_AUDIO_VIDEO_FAILURE:40013,UNSUBSCRIBE_MEDIA_FAILURE:40014,UNSUBSCRIBE_FILE_FAILURE:40015,UNSUBSCRIBE_SCREEN_FAILURE:40016,UNPUBLISH_AUDIO_VIDEO_FAILURE:40019,STOP_MEDIA_FAILURE:40020,STOP_FILE_FAILURE:40021,STOP_SCREEN_FAILURE:40022,
UDP_CONNECTION_FAILED:40023,UDP_CONNECTION_INTERRUPT:40024};L=L||{};L.aexInstance=void 0;
(function(){var c={cipher:function(a,d){for(var b=d.length/4-1,e=[[],[],[],[]],f=0;16>f;f++)e[f%4][Math.floor(f/4)]=a[f];e=c.addRoundKey(e,d,0,4);for(f=1;f<b;f++)e=c.subBytes(e,4),e=c.shiftRows(e,4),e=c.mixColumns(e,4),e=c.addRoundKey(e,d,f,4);e=c.subBytes(e,4);e=c.shiftRows(e,4);e=c.addRoundKey(e,d,b,4);d=Array(16);for(f=0;16>f;f++)d[f]=e[f%4][Math.floor(f/4)];return d},keyExpansion:function(a){for(var d=a.length/4,b=d+6,e=Array(4*(b+1)),f=Array(4),h=0;h<d;h++)e[h]=[a[4*h],a[4*h+1],a[4*h+2],a[4*
h+3]];for(h=d;h<4*(b+1);h++){e[h]=Array(4);for(a=0;4>a;a++)f[a]=e[h-1][a];if(0==h%d)for(f=c.subWord(c.rotWord(f)),a=0;4>a;a++)f[a]^=c.rCon[h/d][a];else 6<d&&4==h%d&&(f=c.subWord(f));for(a=0;4>a;a++)e[h][a]=e[h-d][a]^f[a]}return e},subBytes:function(a,d){for(var b=0;4>b;b++)for(var e=0;e<d;e++)a[b][e]=c.sBox[a[b][e]];return a},shiftRows:function(a,d){for(var b=Array(4),c=1;4>c;c++){for(var f=0;4>f;f++)b[f]=a[c][(f+c)%d];for(f=0;4>f;f++)a[c][f]=b[f]}return a},mixColumns:function(a,d){for(d=0;4>d;d++){for(var b=
Array(4),c=Array(4),f=0;4>f;f++)b[f]=a[f][d],c[f]=a[f][d]&128?a[f][d]<<1^283:a[f][d]<<1;a[0][d]=c[0]^b[1]^c[1]^b[2]^b[3];a[1][d]=b[0]^c[1]^b[2]^c[2]^b[3];a[2][d]=b[0]^b[1]^c[2]^b[3]^c[3];a[3][d]=b[0]^c[0]^b[1]^b[2]^c[3]}return a},addRoundKey:function(a,d,b,c){for(var e=0;4>e;e++)for(var h=0;h<c;h++)a[e][h]^=d[4*b+h][e];return a},subWord:function(a){for(var d=0;4>d;d++)a[d]=c.sBox[a[d]];return a},rotWord:function(a){for(var d=a[0],b=0;3>b;b++)a[b]=a[b+1];a[3]=d;return a},sBox:[99,124,119,123,242,107,
111,197,48,1,103,43,254,215,171,118,202,130,201,125,250,89,71,240,173,212,162,175,156,164,114,192,183,253,147,38,54,63,247,204,52,165,229,241,113,216,49,21,4,199,35,195,24,150,5,154,7,18,128,226,235,39,178,117,9,131,44,26,27,110,90,160,82,59,214,179,41,227,47,132,83,209,0,237,32,252,177,91,106,203,190,57,74,76,88,207,208,239,170,251,67,77,51,133,69,249,2,127,80,60,159,168,81,163,64,143,146,157,56,245,188,182,218,33,16,255,243,210,205,12,19,236,95,151,68,23,196,167,126,61,100,93,25,115,96,129,79,220,
34,42,144,136,70,238,184,20,222,94,11,219,224,50,58,10,73,6,36,92,194,211,172,98,145,149,228,121,231,200,55,109,141,213,78,169,108,86,244,234,101,122,174,8,186,120,37,46,28,166,180,198,232,221,116,31,75,189,139,138,112,62,181,102,72,3,246,14,97,53,87,185,134,193,29,158,225,248,152,17,105,217,142,148,155,30,135,233,206,85,40,223,140,161,137,13,191,230,66,104,65,153,45,15,176,84,187,22],rCon:[[0,0,0,0],[1,0,0,0],[2,0,0,0],[4,0,0,0],[8,0,0,0],[16,0,0,0],[32,0,0,0],[64,0,0,0],[128,0,0,0],[27,0,0,0],[54,
0,0,0]],Ctr:{}};c.Ctr.encrypt=function(a,d,b){d=d||"talk_2018_@beijing_20180310_talk_2018_@beijing";b=b||256;if(128!=b&&192!=b&&256!=b)return"";a=g.encode(a);d=g.encode(d);var e=b/8,f=Array(e);for(b=0;b<e;b++)f[b]=isNaN(d.charCodeAt(b))?0:d.charCodeAt(b);f=c.cipher(f,c.keyExpansion(f));f=f.concat(f.slice(0,e-16));d=Array(16);b=(new Date).getTime();e=b%1E3;var h=Math.floor(b/1E3),p=Math.floor(65535*Math.random());for(b=0;2>b;b++)d[b]=e>>>8*b&255;for(b=0;2>b;b++)d[b+2]=p>>>8*b&255;for(b=0;4>b;b++)d[b+
4]=h>>>8*b&255;e="";for(b=0;8>b;b++)e+=String.fromCharCode(d[b]);f=c.keyExpansion(f);h=Math.ceil(a.length/16);p=Array(h);for(var m=0;m<h;m++){for(b=0;4>b;b++)d[15-b]=m>>>8*b&255;for(b=0;4>b;b++)d[15-b-4]=m/4294967296>>>8*b;var n=c.cipher(d,f),v=m<h-1?16:(a.length-1)%16+1,w=Array(v);for(b=0;b<v;b++)w[b]=n[b]^a.charCodeAt(16*m+b),w[b]=String.fromCharCode(w[b]);p[m]=w.join("")}a=e+p.join("");return a=k.encode(a)};c.Ctr.decrypt=function(a,d,b){d=d||"talk_2018_@beijing_20180310_talk_2018_@beijing";b=b||
256;if(128!=b&&192!=b&&256!=b)return"";a=k.decode(a);d=g.encode(d);var e=b/8,f=Array(e);for(b=0;b<e;b++)f[b]=isNaN(d.charCodeAt(b))?0:d.charCodeAt(b);f=c.cipher(f,c.keyExpansion(f));f=f.concat(f.slice(0,e-16));d=Array(8);e=a.slice(0,8);for(b=0;8>b;b++)d[b]=e.charCodeAt(b);e=c.keyExpansion(f);f=Math.ceil((a.length-8)/16);b=Array(f);for(var h=0;h<f;h++)b[h]=a.slice(8+16*h,16*h+24);a=b;var p=Array(a.length);for(h=0;h<f;h++){for(b=0;4>b;b++)d[15-b]=h>>>8*b&255;for(b=0;4>b;b++)d[15-b-4]=(h+1)/4294967296-
1>>>8*b&255;var m=c.cipher(d,e),n=Array(a[h].length);for(b=0;b<a[h].length;b++)n[b]=m[b]^a[h].charCodeAt(b),n[b]=String.fromCharCode(n[b]);p[h]=n.join("")}a=p.join("");return a=g.decode(a)};var k={code:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\x3d",encode:function(a,d){var b=[],c="",f=k.code;d=("undefined"==typeof d?0:d)?a.encodeUTF8():a;a=d.length%3;if(0<a)for(;3>a++;)c+="\x3d",d+="\x00";for(a=0;a<d.length;a+=3){var h=d.charCodeAt(a);var g=d.charCodeAt(a+1);var m=d.charCodeAt(a+
2);var n=h<<16|g<<8|m;h=n>>18&63;g=n>>12&63;m=n>>6&63;n&=63;b[a/3]=f.charAt(h)+f.charAt(g)+f.charAt(m)+f.charAt(n)}b=b.join("");return b=b.slice(0,b.length-c.length)+c},decode:function(a,d){d="undefined"==typeof d?!1:d;var b=[],c=k.code;var f=d?a.decodeUTF8():a;for(var h=0;h<f.length;h+=4){var g=c.indexOf(f.charAt(h));var m=c.indexOf(f.charAt(h+1));a=c.indexOf(f.charAt(h+2));var n=c.indexOf(f.charAt(h+3));var v=g<<18|m<<12|a<<6|n;g=v>>>16&255;m=v>>>8&255;v&=255;b[h/4]=String.fromCharCode(g,m,v);64==
n&&(b[h/4]=String.fromCharCode(g,m));64==a&&(b[h/4]=String.fromCharCode(g))}b=b.join("");return d?b.decodeUTF8():b}},g={encode:function(a){a=a.replace(/[\u0080-\u07ff]/g,function(a){a=a.charCodeAt(0);return String.fromCharCode(192|a>>6,128|a&63)});return a=a.replace(/[\u0800-\uffff]/g,function(a){a=a.charCodeAt(0);return String.fromCharCode(224|a>>12,128|a>>6&63,128|a&63)})},decode:function(a){a=a.replace(/[\u00e0-\u00ef][\u0080-\u00bf][\u0080-\u00bf]/g,function(a){a=(a.charCodeAt(0)&15)<<12|(a.charCodeAt(1)&
63)<<6|a.charCodeAt(2)&63;return String.fromCharCode(a)});return a=a.replace(/[\u00c0-\u00df][\u0080-\u00bf]/g,function(a){a=(a.charCodeAt(0)&31)<<6|a.charCodeAt(1)&63;return String.fromCharCode(a)})}};L.aexInstance=c.Ctr})();
L.Utils=function(){var c=void 0,k=!1,g=!1;c={handleMediaPlayOnEvent:function(a,d){try{if(L.Utils.removeEvent(a,"canplay",c.handleMediaPlayOnEvent.bind(null,a,d)),L.Utils.removeEvent(a,"loadedmetadata",c.handleMediaPlayOnEvent.bind(null,a,d)),L.Utils.removeEvent(a,"loadeddata",c.handleMediaPlayOnEvent.bind(null,a,d)),a&&a.play&&"function"===typeof a.play){var b=a.play();b&&b.catch&&"function"===typeof b.catch&&b.catch(function(b){L.Logger.error("[tk-fake-sdk]media play err:",L.Utils.toJsonStringify(b),
d?" , media element id is "+d:" media element:",d?"":a)})}}catch(e){L.Logger.error("[tk-fake-sdk]media play error:",L.Utils.toJsonStringify(e),d?" , media element id is "+d:" media element:",d?"":a)}},handleMediaPauseOnEvent:function(a,d){try{if(L.Utils.removeEvent(a,"canplay",c.handleMediaPauseOnEvent.bind(null,a,d)),L.Utils.removeEvent(a,"loadedmetadata",c.handleMediaPauseOnEvent.bind(null,a,d)),L.Utils.removeEvent(a,"loadeddata",c.handleMediaPauseOnEvent.bind(null,a,d)),a&&a.pause&&"function"===
typeof a.pause){var b=a.pause();b&&b.catch&&"function"===typeof b.catch&&b.catch(function(b){L.Logger.error("[tk-fake-sdk]media pause err:",L.Utils.toJsonStringify(b),d?" , media element id is "+d:" media element:",d?"":a)})}}catch(e){L.Logger.error("[tk-fake-sdk]media pause error:",L.Utils.toJsonStringify(e),d?" , media element id is "+d:" media element:",d?"":a)}}};return{addEvent:function(a,d,b,c){a.addEventListener?a.addEventListener(d,b,void 0!=c&&null!=c?c:!1):a.attachEvent?a.attachEvent("on"+
d,b):a["on"+d]=b},removeEvent:function(a,d,b,c){a.removeEventListener?a.removeEventListener(d,b,void 0!=c&&null!=c?c:!1):a.detachEvent?a.detachEvent("on"+d,b):a["on"+d]=null},toJsonStringify:function(a,d){if(void 0!=d&&!d||!a)return a;try{if("object"!==typeof a)return a;var b=JSON.stringify(a);b?a=b:L.Logger.debug("[tk-fake-sdk]toJsonStringify:data is not json!")}catch(e){L.Logger.debug("[tk-fake-sdk]toJsonStringify:data is not json!")}return a},toJsonParse:function(a,d){if(void 0!=d&&!d||!a)return a;
try{if("string"!==typeof a)return a;var b=JSON.parse(a);b?a=b:L.Logger.debug("[tk-fake-sdk]toJsonParse:data is not json string!")}catch(e){L.Logger.debug("[tk-fake-sdk]toJsonParse:data is not json string!")}return a},encrypt:function(a,d,b,c){if(!a)return a;b=b||TK.hexEncryptDecryptKey;c=c||TK.hexEncryptDecryptBit;d=void 0!=d?d:"talk_2018_@beijing";a=L.aexInstance.encrypt(a,b,c);return d+a+d},decrypt:function(a,d,b,c){if(!a)return a;b=b||TK.hexEncryptDecryptKey;c=c||TK.hexEncryptDecryptBit;a=a.replace(new RegExp(void 0!=
d?d:"talk_2018_@beijing","gm"),"");return L.aexInstance.decrypt(a,b,c)},mediaPlay:function(a){var d=void 0;a&&"string"===typeof a?a=document.getElementById(a):a&&/(audio|video)/g.test(a.nodeName.toLowerCase())&&a.getAttribute&&"function"===typeof a.getAttribute&&(d=a.getAttribute("id"));a&&/(audio|video)/g.test(a.nodeName.toLowerCase())&&(0!==a.readyState?c.handleMediaPlayOnEvent(a,d):(L.Utils.removeEvent(a,"canplay",c.handleMediaPlayOnEvent.bind(null,a,d)),L.Utils.removeEvent(a,"loadedmetadata",
c.handleMediaPlayOnEvent.bind(null,a,d)),L.Utils.removeEvent(a,"loadeddata",c.handleMediaPlayOnEvent.bind(null,a,d)),L.Utils.addEvent(a,"canplay",c.handleMediaPlayOnEvent.bind(null,a,d)),L.Utils.addEvent(a,"loadedmetadata",c.handleMediaPlayOnEvent.bind(null,a,d)),L.Utils.addEvent(a,"loadeddata",c.handleMediaPlayOnEvent.bind(null,a,d))))},mediaPause:function(a){var d=void 0;a&&"string"===typeof a?a=document.getElementById(a):a&&/(audio|video)/g.test(a.nodeName.toLowerCase())&&a.getAttribute&&"function"===
typeof a.getAttribute&&(d=a.getAttribute("id"));a&&/(audio|video)/g.test(a.nodeName.toLowerCase())&&(0!==a.readyState?c.handleMediaPauseOnEvent(a,d):(L.Utils.removeEvent(a,"canplay",c.handleMediaPauseOnEvent.bind(null,a,d)),L.Utils.removeEvent(a,"loadedmetadata",c.handleMediaPauseOnEvent.bind(null,a,d)),L.Utils.removeEvent(a,"loadeddata",c.handleMediaPauseOnEvent.bind(null,a,d)),L.Utils.addEvent(a,"canplay",c.handleMediaPauseOnEvent.bind(null,a,d)),L.Utils.addEvent(a,"loadedmetadata",c.handleMediaPauseOnEvent.bind(null,
a,d)),L.Utils.addEvent(a,"loadeddata",c.handleMediaPauseOnEvent.bind(null,a,d))))},localStorage:{setItem:function(a,d){try{window.localStorage?window.localStorage.setItem?window.localStorage.setItem(a,d):L.Logger.warning("[tk-fake-sdk]Browser does not support localStorage.setItem , key is "+a+" , value is "+d+"!"):k||(k=!0,L.Logger.warning("[tk-fake-sdk]Browser does not support localStorage!"))}catch(b){k||(k=!0,L.Logger.warning("[tk-fake-sdk]Browser does not support localStorage , error info:",L.Utils.toJsonStringify(b)))}},
getItem:function(a){try{if(window.localStorage){if(window.localStorage.getItem)return window.localStorage.getItem(a);L.Logger.warning("[tk-fake-sdk]Browser does not support localStorage.getItem , key is "+a+" !");return""}k||(k=!0,L.Logger.warning("[tk-fake-sdk]Browser does not support localStorage!"));return""}catch(d){return k||(k=!0,L.Logger.warning("[tk-fake-sdk]Browser does not support localStorage , error info:",L.Utils.toJsonStringify(d))),""}},removeItem:function(a){try{if(window.localStorage){if(window.localStorage.removeItem)return window.localStorage.removeItem(a);
L.Logger.warning("[tk-fake-sdk]Browser does not support localStorage.removeItem , key is "+a+" !");return""}k||(k=!0,L.Logger.warning("[tk-fake-sdk]Browser does not support localStorage!"));return""}catch(d){return k||(k=!0,L.Logger.warning("[tk-fake-sdk]Browser does not support localStorage , error info:",L.Utils.toJsonStringify(d))),""}}},sessionStorage:{setItem:function(a,d){try{window.sessionStorage?window.sessionStorage.setItem?window.sessionStorage.setItem(a,d):L.Logger.warning("[tk-fake-sdk]Browser does not support sessionStorage.setItem , key is "+
a+" , value is "+d+"!"):g||(g=!0,L.Logger.warning("[tk-fake-sdk]Browser does not support sessionStorage!"))}catch(b){g||(g=!0,L.Logger.warning("[tk-fake-sdk]Browser does not support sessionStorage , error info:",L.Utils.toJsonStringify(b)))}},getItem:function(a){try{if(window.sessionStorage){if(window.sessionStorage.getItem)return window.sessionStorage.getItem(a);L.Logger.warning("[tk-fake-sdk]Browser does not support sessionStorage.getItem , key is "+a+" !");return""}g||(g=!0,L.Logger.warning("[tk-fake-sdk]Browser does not support sessionStorage!"));
return""}catch(d){return g||(g=!0,L.Logger.warning("[tk-fake-sdk]Browser does not support sessionStorage , error info:",L.Utils.toJsonStringify(d))),""}},removeItem:function(a){try{if(window.sessionStorage){if(window.sessionStorage.removeItem)return window.sessionStorage.removeItem(a);L.Logger.warning("[tk-fake-sdk]Browser does not support sessionStorage.removeItem , key is "+a+" !");return""}g||(g=!0,L.Logger.warning("[tk-fake-sdk]Browser does not support sessionStorage!"));return""}catch(d){return g||
(g=!0,L.Logger.warning("[tk-fake-sdk]Browser does not support sessionStorage , error info:",L.Utils.toJsonStringify(d))),""}}}}}(L);TK=TK||{};var JsSocket={};
TK.fakeScoketIO=function(c){var k={},g={},a=0,d={};k.bindAwitSocketListEvent=function(){for(var a in d){var c=d[a];delete d[a];k.on(a,c)}};k.on=function(a,c){if(a)if(c){var b=function(){for(var b=[],d={},e=0;e<arguments.length;e++)b[e]="string"===typeof arguments[e]?L.Utils.toJsonParse(arguments[e]):arguments[e],d[e]=b[e];L.Logger.debug("[tk-fake-sdk]logMessage info: receive event("+a+") callback arguments json is "+L.Utils.toJsonStringify(d));TK.global.fakeJsSdkInitInfo.mobileInfo.isSendLogMessageToProtogenesis&&"MobileNativeRoom"===
TK.SDKNATIVENAME&&"printLogMessage"!==a&&"JsSocketCallback"!==a&&k.emit("printLogMessage",L.Utils.toJsonStringify({eventType:a,receiveData:b}));c.apply(c,b)};switch(TK.SDKNATIVENAME){case "QtNativeClientRoom":if(window.qtContentTkClient)try{L.Logger.debug("[tk-fake-sdk]Bind qt event , event name is "+a),window.qtContentTkClient[a].connect(b)}catch(h){L.Logger.error("[tk-fake-sdk]Bind qt event fail , event name is "+a,h)}else L.Logger.warning("[tk-fake-sdk]window.qtContentTkClient is not exist , save event to list awit socket bind , event name is "+
a+" !"),d[a]=b;break;case "MobileNativeRoom":L.Logger.debug("[tk-fake-sdk]Bind mobile event , event name is "+a);JsSocket[a]=b;break;default:L.Logger.error("[tk-fake-sdk]socket.on:room is not init , sdkNativeName is "+TK.SDKNATIVENAME+"!")}}else L.Logger.error("[tk-fake-sdk]socket bind event callback is must exist!");else L.Logger.error("[tk-fake-sdk]socket bind event name is must exist!")};k.emit=function(b,c,d){if("printLogMessage"===b&&"MobileNativeRoom"!==TK.SDKNATIVENAME)L.Logger.warning("[tk-fake-sdk]socket.emit event name is printLogMessage , not emit event , because event triggering must be in the mobile app environment.");
else{var e={};L.Logger.debug("[tk-fake-sdk]socket.emit event name is "+b);if(d&&"function"===typeof d){var f=++a;g[f]=d;e.callbackID=f}if("object"===typeof c)for(var k in c)"callbackID"!==k&&(e[k]=c[k]);else if("string"===typeof c)if(d=L.Utils.toJsonParse(c),"object"===typeof d)for(k in d)"callbackID"!==k&&(e[k]=d[k]);else void 0!==e.callbackID?e.params=c:e=c;else void 0!==e.callbackID?e.params=c:e=c;switch(TK.SDKNATIVENAME){case "QtNativeClientRoom":if(window.qtContentTkClient)if(window.qtContentTkClient["onWeb_"+
b])if(L.Logger.debug("[tk-fake-sdk]socket.emit:window.qtContentTkClient.onWeb_"+b+" has been performed!"),void 0===e)window.qtContentTkClient["onWeb_"+b]("");else"object"===typeof e&&(e=L.Utils.toJsonStringify(e)),window.qtContentTkClient["onWeb_"+b](e);else L.Logger.error("[tk-fake-sdk]socket.emit:window.qtContentTkClient.onWeb_"+b+" is not exist!");else L.Logger.error("[tk-fake-sdk]window.qtContentTkClient is not exist!");break;case "MobileNativeRoom":c=TK.global.fakeJsSdkInitInfo.mobileInfo.clientType;
if(void 0===c||null===c)window.JSWhitePadInterface||window.JSVideoWhitePadInterface?c=L.Constant.clientType.android:window.webkit&&window.webkit.messageHandlers&&(c=L.Constant.clientType.ios);switch(c){case L.Constant.clientType.ios:window.webkit&&window.webkit.messageHandlers&&window.webkit.messageHandlers[b]?(L.Logger.debug("[tk-fake-sdk]socket.emit:window.webkit.messageHandlers."+b+".postMessage has been performed!"),void 0===e?window.webkit.messageHandlers[b].postMessage({data:""}):("object"===
typeof e&&(e=L.Utils.toJsonStringify(e)),window.webkit.messageHandlers[b].postMessage({data:e}))):L.Logger.error("[tk-fake-sdk]socket.emit:window.webkit.messageHandlers."+b+".postMessage is not exist!");break;case L.Constant.clientType.android:if("_videoWhiteboardPage"===TK.extendSendInterfaceName)if(window.JSVideoWhitePadInterface&&window.JSVideoWhitePadInterface[b])if(L.Logger.debug("[tk-fake-sdk]socket.emit:window.JSVideoWhitePadInterface."+b+" has been performed!"),void 0===e)window.JSVideoWhitePadInterface[b]("");
else"object"===typeof e&&(e=L.Utils.toJsonStringify(e)),window.JSVideoWhitePadInterface[b](e);else L.Logger.error("[tk-fake-sdk]socket.emit:window.JSVideoWhitePadInterface."+b+" is not exist!");else if(window.JSWhitePadInterface&&window.JSWhitePadInterface[b])if(L.Logger.debug("[tk-fake-sdk]socket.emit:window.JSWhitePadInterface."+b+" has been performed!"),void 0===e)window.JSWhitePadInterface[b]("");else"object"===typeof e&&(e=L.Utils.toJsonStringify(e)),window.JSWhitePadInterface[b](e);else L.Logger.error("[tk-fake-sdk]socket.emit:window.JSWhitePadInterface."+
b+" is not exist!");break;default:L.Logger.error("[tk-fake-sdk]clientType is undefinable , will not be able to execute method "+b+" , clientType is "+c)}break;default:L.Logger.error("[tk-fake-sdk]socket.emit:room is not init , sdkNativeName is "+TK.SDKNATIVENAME+"!")}}};k.on("JsSocketCallback",function(a,c){if(g[a]){if("function"===typeof g[a])g[a](c);delete g[a]}});return k};
